### ISSUE TITLE
How to install it

### ISSUE THREAD

**Issue by seyhadot** [maybewaityou/idea-flyme-plugin#1]
i have download the zip file but i can't install on intellij

**Comment by maybewaityou** [comment]
I’m sorry, I published the plugin is Nightly channel and I bad republished
a Stable channel yesterday. Now you can install the plugin form disk.

Preferences -> Plugins -> Install Plugin Form Disk, select flyme-xxxx.zip,
and restart IDE.


seyhadot <notifications@github.com> 于2020年3月31日周二 下午10:00写道：
